### PR TITLE
Fix SyntaxError in cheatsheet for dictionaries

### PR DESCRIPTION
**Pull request by frenzymadness**
The svg is correct but I don't have the proper font so the generated pdf does not look good. Is there anybody who can help me and regenerate the pdf for me? Cc @Kobzol @encukou and @adelpopelkova

### CODE REVIEW

**Comment by Kobzol** [comment]
Try this:
[dicts-cs.pdf](https://github.com/pyvec/cheatsheets/files/7511532/dicts-cs.pdf)

**Comment by frenzymadness** [comment]
Thanks a lot, this is now ready to be merged.

**Review by adelpopelkova — APPROVED** [review]
It looks really good. Thank you.

**Comment by frenzymadness** [comment]
@encukou or @honzajavorek could you please merge this?

**Pull request merged**
